feat: CHECKS ITERATION PARAMETERS WHEN GETTING LLCMODEL DATASETS
MITgcm/xmitgcm pull request #240
Opened 2020-11-12 18:00 UTC by fraserwg

When loading datasets using the llcreader the user is able to specify the iteration start, stop and step. These can also be specified as attributes in the `BaseLLCModel`. This commit introduces a check that compares the `iter_start` and `iter_step` fed into `get_dataset` with the `BaseLLCModel` attributes. If they are found to be incompatible a warning is triggered.

A warning over an Error was chosen as subsuquent code may still execute successfully even if there is a mismatch between the user specified and `BaseLLCModel` derived values for `iter_start` and `iter_stop`.

2020-11-12 18:01 UTC, fraserwg commented
This implements my request from issue #235

2020-11-12 18:20 UTC, rabernat commented
Thanks a lot for this! We really appreciate your willingness to dive into xmitgcm.

We strive for high test coverage for this package. Therefore, you will need to add a test for this new feature. You will probably want to use the pytest warnings mechanism: https://docs.pytest.org/en/3.0.5/recwarn.html.

2020-11-16 01:03 UTC, rabernat commented
It looks like there is now a merge conflict here, since we recently merged #231. Perhaps @timothyas can help you sort it out?

2020-11-16 16:22 UTC, timothyas commented
No problem, it seems like the merge conflicts are all gone - thanks @fraserwg! I think this looks good to me, I just have one minor request to add to the tests, but then I think it's good to go.

2020-11-16 16:24 UTC, timothyas requested changes
Could you add a test which checks for this warning while calling `get_dataset`? For example at the bottom of this test:
https://github.com/MITgcm/xmitgcm/blob/04ec9fb7a819181545dcb455f8553bb5695bbcf6/xmitgcm/test/test_llcreader.py#L127
just another `with pytest.warns` check as you did for the others

2020-11-16 16:28 UTC, rabernat requested changes
Thanks for your work on this @fraserwg and for your patience as we review your PR.

2020-11-16 16:28 UTC, rabernat commented on xmitgcm/test/test_llcreader.py
> +        ecco_portal_model._check_iter_start(ecco_portal_model.iter_start + ecco_portal_model.iter_step) # Should give no warning
This is not quite what I had in mind for a test. You should not call private functions (e.g. `._check_iter_start`) from the test suite. Instead, you should call the public API (e.g. `get_dataset`) as suggested by @timothyas.

2020-11-17 15:45 UTC, fraserwg commented on xmitgcm/test/test_llcreader.py
> +        ecco_portal_model._check_iter_start(ecco_portal_model.iter_start + ecco_portal_model.iter_step) # Should give no warning
Sure, I've rewritten the tests to call `get_dataset` but the ECCO Data Portal is currently down. I'll push the changes when I've verified they work locally 👍

2020-11-20 18:26 UTC, rabernat commented
I think the test failure is a fluke, so I'm going to merge this now. Thanks for another great contribution!

2020-11-20 18:26 UTC, merged