WIP: full size xg and yg
MITgcm/xmitgcm pull request #246
Opened 2021-01-06 17:03 UTC by AaronDavidSchneider

This PR picks up on PR #195 and is currently WIP.
I plan to keep this PR minimal and not pick up the ability to reshape a dataset in tiles of a specified shape.
This PR only extends xg and yg to their full size.

2021-01-06 18:56 UTC, AaronDavidSchneider commented
I will delay this PR until PR #98 is merged. 
It makes no sense to do the work twice 😀

2021-03-11 15:44 UTC, AaronDavidSchneider commented
Hi @rabernat,  

I think I found a solution. In the current version of this PR we are extending extending i_g and j_g to nx + 1.
I think my implementation is straight forward and quite easy.

I tested it with a cs grid. But it should also work with llc.

Cheers
Aaron

2021-03-11 16:41 UTC, raphaeldussin commented on xmitgcm/utils.py
> +                        if field in outerx_vars or field in outerxy_vars or field in outery_vars:
or a more concise way:
```python
if field in outerx_vars + outerxy_vars + outery_vars:
```

2021-03-11 16:43 UTC, raphaeldussin commented on xmitgcm/utils.py
> +                                          np.arange(nxouter)),
this is only true because nx = ny in CS and LLC **faces**

2021-03-11 16:47 UTC, raphaeldussin commented
I think this PR solves the issues of my previous implementation of this utility function

2021-03-11 19:56 UTC, AaronDavidSchneider reviewed
Thanks @raphaeldussin for your feedback! I changed it to match your feedback.

2021-03-11 19:56 UTC, AaronDavidSchneider commented on xmitgcm/utils.py
> +                                          np.arange(nxouter)),
that makes sense. I changed it for the else case (not cs and not llc).
It seems that it was also wrong before

2021-03-25 09:45 UTC, AaronDavidSchneider commented
Hi @rabernat, @raphaeldussin, just a quick reminder that my work on this PR is finished.

2021-04-13 11:50 UTC, AaronDavidSchneider commented
Hi, just another casual reminder @rabernat and @raphaeldussin (sorry for bothering).

2021-04-13 12:13 UTC, rabernat commented
Thanks for the reminder @AaronDavidSchneider, and sorry for taking so long to review! We really appreciate your contribution. I will do my best to have a look this week.

2021-04-13 12:17 UTC, rabernat requested changes
This is really great!

My one central concern is that we don't have a test. @raphaeldussin - do any of the test cases contain the needed input files to test this code?

2021-04-13 12:17 UTC, rabernat commented on xmitgcm/utils.py
> +                    tmp = rawfields[field][:, :, :, :-1].squeeze()
```suggestion
                    tmp = rawfields[field][..., :-1].squeeze()
```

2021-04-13 12:17 UTC, rabernat commented on xmitgcm/utils.py
> +                    tmp = rawfields[field][:, :, :-1, :].squeeze()
```suggestion
                    tmp = rawfields[field][..., :-1, :].squeeze()
```

2021-04-13 12:17 UTC, rabernat commented on xmitgcm/utils.py
> +                    tmp = rawfields[field][:, :, :, :].squeeze()
```suggestion
                    tmp = rawfields[field].squeeze()
```

2021-04-13 12:17 UTC, rabernat commented on xmitgcm/utils.py
> +                    tmp = rawfields[field][:, :, :-1, :-1].squeeze()
```suggestion
                    tmp = rawfields[field][..., :-1, :-1].squeeze()
```

2021-04-13 12:42 UTC, AaronDavidSchneider commented
Thanks for your comments @rabernat!

2021-04-13 12:54 UTC, AaronDavidSchneider commented
Regarding the tests:
It should be feasible to check if the XC and YC values are in the middle of the XG and YG values of outer=True. 

What do you think?

2021-04-13 13:16 UTC, rabernat commented
So I looked it up, and it seems that we already have a good test for the `get_grid_from_input`

https://github.com/MITgcm/xmitgcm/blob/4a9c748c2e7cf140d85efee8851cac9d7e7c45e0/xmitgcm/test/test_utils.py#L961

To this test you should add a section that calls the function with `outer=True`.

> It should be feasible to check if the XC and YC values are in the middle of the XG and YG values of outer=True.

No, I would not recommend that.  The data are coming from files hosted in the test data repo, so I would not make assumptions about the values. You just want to check that the arrays are the right shape.

Do you know how to run the test suite? Just run `pytest` from the root directory.

2021-04-13 13:47 UTC, raphaeldussin commented
@rabernat we should have the CS grid on figshare, see https://github.com/MITgcm/xmitgcm/blob/4a9c748c2e7cf140d85efee8851cac9d7e7c45e0/xmitgcm/test/test_xmitgcm_common.py#L137

let me know if there is an issue with it

2021-04-13 14:53 UTC, AaronDavidSchneider commented
I added some tests that fail. However, I don't know why. I have the bad feeling that outer=True only works for the cs geometry.
I think I need help with fixing the bug, since I am not familiar with aste or llc :D 
Thank you for your time!

2021-04-13 15:11 UTC, rabernat commented
> I added some tests that fail. However, I don't know why. I have the bad feeling that outer=True only works for the cs geometry.

This is why we have tests: to find cases we did not consider before users do!

I am hoping @raphaeldussin can help you fix the bug. He knows this part of the code base the best. For reference, here is the test failure:

<details>

```
        ds_outer = get_grid_from_input(dirname + '/' + expected['gridfile'],
                                 geometry=expected['geometry'],
                                 dtype=np.dtype('d'), endian='>',
                                 use_dask=usedask,
                                 extra_metadata=md,
>                                outer=True)

xmitgcm/test/test_utils.py:978: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
xmitgcm/utils.py:1452: in get_grid_from_input
    padded = _pad_array(tmp, file_metadata, face=face)
xmitgcm/utils.py:1229: in _pad_array
    (pad_before, data), axis=0)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

args = ((array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
  ...       ],
       [-38.        , -37.93939671, -37.8460971 , ...,  51.8460971 ,
         51.93939671,  52.        ]])),)
kwargs = {'axis': 0}
relevant_args = (array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
   ....        ],
       [-38.        , -37.93939671, -37.8460971 , ...,  51.8460971 ,
         51.93939671,  52.        ]]))

>   ???
E   ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 270 and the array at index 1 has size 271
```

</details>

2021-05-04 10:30 UTC, AaronDavidSchneider commented
Hi @raphaeldussin,
could you give me some feedback on how we can fix this PR for llc geometry?
Alternatively, we could raise a notimplementederror if the outer argument is used with the llc geometry.
Thanks!

2021-05-04 20:19 UTC, raphaeldussin commented
https://github.com/AaronDavidSchneider/xmitgcm/pull/1 should solve the problem.

2021-05-05 04:48 UTC, AaronDavidSchneider commented
Thanks @raphaeldussin for your feedback and work on this PR.
It should work now.

2021-05-05 15:45 UTC, raphaeldussin requested changes

2021-05-05 15:45 UTC, raphaeldussin commented on xmitgcm/test/test_utils.py
> +    ds_outer = get_grid_from_input(dirname + '/' + expected['gridfile'],
we could make the test more compact by using a pytest.mark.parameterize on outer

2021-05-05 15:45 UTC, raphaeldussin commented on xmitgcm/test/test_utils.py
>      if expected['geometry'] == 'llc':
we would also want to test this with cs geometry

2021-05-05 15:45 UTC, raphaeldussin commented on xmitgcm/utils.py
> +    if outer:
suggest using outer_vars = ['DXC',...] if outer else []

2021-05-05 15:46 UTC, raphaeldussin commented
getting very close to the finish line @AaronDavidSchneider

2021-05-05 16:19 UTC, AaronDavidSchneider commented on xmitgcm/test/test_utils.py
>      if expected['geometry'] == 'llc':
I think I don't understand what you mean here.

2021-05-05 16:19 UTC, AaronDavidSchneider commented on xmitgcm/test/test_utils.py
> +    ds_outer = get_grid_from_input(dirname + '/' + expected['gridfile'],
Good Idea. Did that.

2021-05-05 16:19 UTC, AaronDavidSchneider commented on xmitgcm/utils.py
> +    if outer:
Good idea.

2021-05-05 16:21 UTC, AaronDavidSchneider commented
Thanks for your feedback @raphaeldussin. I tried to address the proposed changes. I still have one open question (see above).

2021-05-05 20:05 UTC, raphaeldussin requested changes

2021-05-06 06:50 UTC, AaronDavidSchneider commented
So I just had a look into the llc checks in `test_get_grid_from_input` and tried to come up with a simple test that would do the same for the cs geometry.
However, the cs geometry is slightly different and I would need more knowledge about the raw data. E.g.
```py
xc1 = read_raw_data(grid1, dtype=np.dtype('>d'), shape=(ny1, nx),
                            partial_read=True)
```
does not work.

I would suggest, that we merge this PR first (once its ready) and work on cs grid checks afterwards, since these checks are not really related to this PR anyway.


I would be happy to open up a new PR to work on these checks. However, I would need your help @raphaeldussin for the `read_raw_data` part.

2021-05-06 14:35 UTC, raphaeldussin commented
I think this test on the values is important so we preserve the answers in any future code changes.
inferring/reading the raw data can do this way: 

`du -b file.bin` and divide by 8 (number of bytes in double precision, which is the format used for grids), then nx+1 = 33 twice
since you have square faces of cs32 and you get 18 which is your number of variables. Then

read all variables:
```python
raw = read_raw_data('grid_cs32.face001.bin', np.dtype('>d'), (18,33,33))
```

read only first one:
```python
raw = read_raw_data('grid_cs32.face001.bin', np.dtype('>d'), (33,33), partial_read=True)
```

read second:
```python
raw = read_raw_data('grid_cs32.face001.bin', np.dtype('>d'), (33,33), partial_read=True, offset=(33*33*8))
```

from there you should be able to add a section to the test for CS geometry.

2021-05-06 17:16 UTC, AaronDavidSchneider commented
Thanks for the explanation @raphaeldussin! I took the llc check and adapted it for the CS grid. What do you think?

2021-05-06 18:05 UTC, raphaeldussin approved these changes

2021-05-06 18:06 UTC, raphaeldussin commented
LGTM! @rabernat are you good with this as well?

2021-05-10 04:27 UTC, AaronDavidSchneider commented
Hi @rabernat, could you have a final look on this PR?
Thanks!

2021-05-17 12:24 UTC, AaronDavidSchneider commented
Hi @rabernat, could you have a final look on this PR?
Thanks!

2021-06-13 13:37 UTC, AaronDavidSchneider commented
Just another kind reminder @rabernat.

2021-07-27 13:32 UTC, AaronDavidSchneider commented
Hi @rabernat,
is there any possibility that this could be merged soon?

2021-07-27 13:36 UTC, rabernat reviewed
Sorry for being extremely slow here. Just one question, then LGTM.

2021-07-27 13:36 UTC, rabernat commented on xmitgcm/test/test_utils.py
> +        xc1 = read_raw_data(grid1, dtype=np.dtype('>d'), shape=(nx, nx),
Is this dtype (`'>d'`) always the same for every mitgcm run everywhere? If not, we will need a parameter to configure it.

2021-07-27 13:57 UTC, AaronDavidSchneider commented on xmitgcm/test/test_utils.py
> +        xc1 = read_raw_data(grid1, dtype=np.dtype('>d'), shape=(nx, nx),
Oh well that's a good question! I just used what @raphaeldussin suggested above. Maybe @raphaeldussin knows better?

2021-07-28 14:56 UTC, raphaeldussin commented on xmitgcm/test/test_utils.py
> +        xc1 = read_raw_data(grid1, dtype=np.dtype('>d'), shape=(nx, nx),
It would be easy to add extra keys (`endianness`, `precision`) to _grids here https://github.com/MITgcm/xmitgcm/blob/c793ecceba5393aac9be0bbdf91a53a3175ecccc/xmitgcm/test/test_xmitgcm_common.py#L175 and pass them down to the test.

AFAIK all the grid files are written in double precision and big-endian, I'm not sure MITgcm can read any other format.

2021-07-28 15:13 UTC, rabernat commented on xmitgcm/test/test_utils.py
> +        xc1 = read_raw_data(grid1, dtype=np.dtype('>d'), shape=(nx, nx),
> AFAIK all the grid files are written in double precision and big-endian, I'm not sure MITgcm can read any other format.

If this is true, then we can save ourselves the trouble and just merge this as is. Is there any evidence in the MITgcm source code?

2021-07-28 15:54 UTC, AaronDavidSchneider commented on xmitgcm/test/test_utils.py
> +        xc1 = read_raw_data(grid1, dtype=np.dtype('>d'), shape=(nx, nx),
I think MITgcm is per default big endian and double precision.
But I think you could in principle change it.

2021-07-28 15:58 UTC, raphaeldussin commented on xmitgcm/test/test_utils.py
> +        xc1 = read_raw_data(grid1, dtype=np.dtype('>d'), shape=(nx, nx),
let's put in the extra keys, I doubt we'll ever use other values but we'll get it covered. Did not find hard restrictions in MITgcm so far.

2021-07-28 16:42 UTC, AaronDavidSchneider commented on xmitgcm/test/test_utils.py
> +        xc1 = read_raw_data(grid1, dtype=np.dtype('>d'), shape=(nx, nx),
Sounds good to me. Will do so.

2021-07-28 16:53 UTC, AaronDavidSchneider commented
Added precision and endianness to grid common.
Thanks a lot @rabernat and @raphaeldussin!

2021-07-29 06:43 UTC, rabernat approved these changes
Fantastic!

Reading the code, I realized I don't like how we have separate parameters for `dtype` and `endian`. We can handle endianness as part of dtype, so this is unnecessary. However, that predates your PR, so it doesn't have to be fixed here.

2021-07-29 06:43 UTC, merged