fix variable metadata typos
MITgcm/xmitgcm pull request #249
Opened 2021-01-12 00:19 UTC by rabernat

Picks up where #247 left off.

2021-01-12 00:21 UTC, timothyas commented
Thanks for taking care of this!

2021-01-12 00:22 UTC, rabernat commented
When you make a 🤦  the best thing to do is fix it!

2021-01-12 01:02 UTC, timothyas commented on xmitgcm/variables.py
> +        units='dJ/(m s-1)')),
@mjlosch can you confirm the ADJ precip and runoff units? I made these changes based on what they are in the exf package.

2021-01-12 01:13 UTC, timothyas commented
I just went through and made some changes directly. I think it's good once @mjlosch confirms a couple of variables as noted

2021-01-12 08:41 UTC, mjlosch requested changes
Except for "psu" I am fine with the changes and apologise for my sloppiness.

2021-01-12 08:41 UTC, mjlosch commented on xmitgcm/variables.py
> +        units='dJ/(m s-1)')),
@timothyas you are right, that was another oversight at my end.

2021-01-12 08:41 UTC, mjlosch commented on xmitgcm/variables.py
> +        units='dJ/psu)')),
Here I disagree, although my solution is not optimal either. Salinity has no units. In particular "psu" (practical salinity unit) is something that should not be used. pss = practical salinity scale is a compromise but also not very good, see e.g. https://www.myroms.org/forum/viewtopic.php?t=294 
If we want to use absolute salinity, the "unit" is g/kg, which again is 1/1000 with no units. In https://github.com/MITgcm/MITgcm/blob/master/model/inc/DYNVARS.h we have "ppt" (parts per thousand), which is again not a unit but just a ratio as it should be. To be consistent, we can change this to dJ/ppt if you like.

2021-01-12 18:06 UTC, timothyas commented on xmitgcm/variables.py
> +        units='dJ/psu)')),
Thanks for another look at all of this @mjlosch! I don't have a strong opinion about what the "units" (or not!) of salinity are labeled as. I put `psu` because at the end of the day it is what the MITgcm diagnostics assigns to the variable `SALT` (and anything involving it like advection of salt, etc), at least for the setups I am using. I see what you're saying about `DYNVARS.h`. My vote is for consistency, and so if we go for e.g. `ppt` here, I would be in favor of opening this discussion in the MITgcm as well to change it there too.

Unless I'm missing something here... Let me know what you think.

2021-01-12 20:20 UTC, mjlosch commented on xmitgcm/variables.py
> +        units='dJ/psu)')),
We should probably go for g/kg, and then open an issue on MITgcm, where the comment need to be changed in DYNVARS.h and the units in diagnostics_main_init.F
@rabernat please decide on the "unit"/non-unit. We can always change it, once the MITgcm code is settled.

2021-01-20 08:12 UTC, mjlosch commented on xmitgcm/variables.py
> +        units='dJ/psu)')),
@timothyas @rabernat 
Yesterday, I talked to @jm-c, @christophernhill, @jrscott, @jahn and we agreed to replace the "units" of salinity by "g/kg" in the MITgcm code, so I suggest to do this here as well anticipating this change ("in vorauseilendem Gehorsam"). I can do that, if you agree.

2021-01-20 16:51 UTC, timothyas commented on xmitgcm/variables.py
> +        units='dJ/psu)')),
That sounds good to me, I'm in favor of g/kg. If @rabernat agrees, we'll want to change it for every salinity instance in variables.py. Thanks @mjlosch

2021-01-21 16:14 UTC, mjlosch approved these changes

2021-01-21 21:22 UTC, timothyas commented
I'm having a hard time trusting my eyes these days, but this looks good to me 👍

2021-01-21 21:36 UTC, rabernat commented
Thanks everybody. I really appreciate the work.

2021-01-21 21:37 UTC, merged